### ISSUE TITLE
Consider adding an arm version

### ISSUE THREAD

**Issue by ivan-kovnatskyi-c54f97a** [zackelia/homebrew-formulae#1]
Thanks for the tool!

I'm using nix-homebrew and I'm getting this when trying to install `bclm`:

```console
Skipping bclm (no bottle for Apple Silicon)
```

**Comment by zackelia** [comment]
Are you sure the tap is configured correctly? I provide a universal binary for both Intel and Apple silicon.

**Comment by ghost** [comment]
Ok, something if probably off when using managing brew in non-traditional way. Thanks!
